version: "3.7"
services:
  # web:
  #   container_name: iim_apache
  #   hostname: iim_apache
  #   build: containers/apache
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - iim-lamp
  #   volumes:
  #     - ./src/:/usr/local/apache2/htdocs
  #     - ./config/:/usr/local/apache2/conf/extra
  nginx:
    container_name: iim_nginx
    hostname: iim_nginx
    image: nginx:1.19
    ports:
      - 80:80
      - 443:443
    networks:
      - iim-lemp
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
  php:
    container_name: iim_php
    hostname: iim_php
    build: 
      context: ./
      dockerfile: ./containers/php/Dockerfile
    networks:
      - iim-lamp
      - iim-lemp
    volumes:
      - ./src/:/var/www
  mysql:
    container_name: iim_mysql
    hostname: iim_mysql
    ports:
      - 3306:3306
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: mydb
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - iim-lamp
      - iim-lemp

networks:
  iim-lamp:
  iim-lemp:
