version: "3.7"
services:
  web:
    container_name: iim_apache
    hostname: iim_apache
    build: containers/apache
    ports:
      - 80:80
      - 443:443
    networks:
      - iim-lamp
    volumes:
      - ./src/:/usr/local/apache2/htdocs
      - ./config/:/usr/local/apache2/conf/extra
  php:
    container_name: iim_php
    hostname: iim_php
    build: containers/php
    networks:
      - iim-lamp
    volumes:
      - ./src/:/var/www
  mysql:
    container_name: iim_mysql
    hostname: iim_mysql
    ports:
      - 3306:3306
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: mydb
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - iim-lamp

networks:
  iim-lamp:
